version: '3'
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: node-complete
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=example
    ports:
      - 3030:80
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - ./app/node_modules
      - ./node:/app
