version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      # setting for not copy node_modules, but this leads to error, comment out for now...
      # - ./app/node_modules
      - ./node:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # setting for not copy node_modules, but this leads to error, comment out for now...
      #- ./app/node_modules
      - ./client:/app
    # polling setting for Docker. activate auto reload when file change.
    environment:
      - CHOKIDAR_USEPOLLING=true
